name: Deploy to VPS

on:
  push:
    branches:
      - master
  deploy:
    runs-on: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/bronesto
            git pull origin master
            pnpm install --production
            pm2 restart bronesto